on:
    push:
        branches:
            - topic/*
        paths-ignore:
        - README.md
        - CHANGELOG.md
        - .grenrc.yml

name: DevelopmentBuild
jobs:
    buildmac:
        name: Linux
        runs-on: ubuntu-latest
        steps:
            - name: Show Environment
              run: set | grep GIT
            - name: Setup Python environment
              uses: actions/setup-python@v4
              with:
                python-version: 3.9.*
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                submodules: recursive
            - name: Create sdkconfig
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -s
            - name: Update version
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -U
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -D
            - name: Package project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -c
            - name: Dev Release
              uses: svenstaro/upload-release-action@latest
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: release/*
                tag: ${{ github.ref }}
                overwrite: true
                prerelease: true
                file_glob: true
