on:
    push:
        branches:
            - dev
        paths-ignore:
        - README.md
        - CHANGELOG.md
        - .grenrc.yml

name: DevelopmentBuild
jobs:
    buildmac:
        name: Linux
        runs-on: ubuntu-latest
        steps:
            - name: Show Environment
              run: set | grep GIT
            - name: Setup Python environment
              uses: actions/setup-python@v4
              with:
                python-version: 3.9.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Update version
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -U
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -D
            - name: Dev Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                 repo_token: "${{ secrets.GITHUB_TOKEN }}"
                 automatic_release_tag: "latest"
                 prerelease: true
                 title: "Development Build"
                 files: release/*
